#include <stdint.h>
#include <stdio.h>

// Automatic state function generated by macros
#define STATE_Define(_STATEFUNC_) void ST_##_STATEFUNC_()
#define STATE_(_stateFUN_)          ST_##_stateFUN_

#define SET_BIT(ADDRESS,BIT)   ADDRESS |=  (1<<BIT)
#define RESET_BIT(ADDRESS,BIT) ADDRESS &= ~(1<<BIT)
#define TOGGLE_BIT(ADDRESS,BIT)  ADDRESS ^=  (1<<BIT)
#define READ_BIT(ADDRESS,BIT) ((ADDRESS) &   (1<<(BIT)))


#define GPIO_PORTA 0x40010800
#define BASE_RCC   0x40021000

#define APB2ENR   *(volatile uint32_t *)(BASE_RCC + 0x18)

#define GPIOA_CRL *(volatile uint32_t *)(GPIO_PORTA + 0x00)
#define GPIOA_CRH *(volatile uint32_t *)(GPIO_PORTA + 0X04)
#define GPIOA_IDR *(volatile uint32_t *)(GPIO_PORTA + 0x08)
#define GPIOA_ODR *(volatile uint32_t *)(GPIO_PORTA + 0x0C)


void Delay(int nCount);
int getPressureVal();
void Set_Alarm_actuator(int i);
// function to sent the reading from pressure sensor to main function
void set_Pressure_Reading(int Pressure_Sensor_Reading);
// function for high pressure detection
void High_Pressure_Detected();
// function for low pressure detection
void Low_Pressure_Detected();

void GPIO_INITIALIZATION ();
